### ISSUE TITLE
Editor crashes when adding a comment to a function parameter

### ISSUE THREAD

**Issue by jtuchsen** [Microsoft/TouchDevelop#244] opened 2015-07-10 21:25 UTC
It's possible to crash the editor by trying to add a comment (or any other imperative statement) while at the beginning of a function parameter, another way to trigger it is to try and add a statement to a record field. Here's a [gif](https://cloud.githubusercontent.com/assets/8864174/8628690/ec26b6e2-2709-11e5-90a7-fa5db6e58ddc.gif) illustrating how to trigger the bug. I investigated and it looks like the bug surfaced when the calculator was changed to show the upper statements bar on the beginning of any line, which is necessary to allow for the "return" statement no doubt.

I have a patch which filters out function parameters and record fields from showing the top statement bar. It's a bit of a band aid solution, but given the statements bar does nothing in both of those scenarios, it's seems right to just hide it and let the documentation stay presented. If you're planning on allowing comments on editor fields or anything else that requires that top bar to be shown, I can fix the crash more directly if you like.

**Comment by millerv** [comment] 2016-01-08 23:52
Given the changes to function parameters and other updates since this bug, I can't seem to reproduce this - Rick, can you see if this still occurs if you try it out?

**Comment by RickGMSR** [comment] 2016-01-11 21:23
I tried to re-create the same script but I could not even insert a comment in the location that he was able to. Inserting comments worked fine without a crash

**Comment by millerv** [comment] 2016-02-02 18:41
Closing issue as no repro.

**Closed by millerv** 2016-02-02 18:41 UTC
Labels: bug, P1
