### ISSUE TITLE
TouchDevelop Hub (selecting a tutorial) :

### ISSUE THREAD

**Issue by MichaelEBraun** [Microsoft/TouchDevelop#203] opened 2015-05-26 17:53 UTC
TouchDevelop Hub (selecting a tutorial) - issue: 

When the user clicks on the tutorial without signing in, the user gets stuck on selecting a skill level. It's not allowing the user to follow a script without selecting a skill level. The default skill level should be beginner with an easy ability to upgrade the user level (this should be represented in the last line of the code... change skill level)

**Comment by millerv** [comment] 2015-11-20 22:51
Can't reproduce this one, closing bug.

**Closed by millerv** 2015-11-20 22:51 UTC
Labels: bug, P2, tutorials
